services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server1
      - server2
      - server3
      - server4
    ports:
      - '3000:80'
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    # network_mode: host
  server1:
    build: ./server
    links:
      - redis
      - redisses
      - cassandra
      # - mongo
    expose:
      - '3000'
    environment:
      - NAME=server1
      - MONGO_URL=mongodb://mongo:27017/sessions
  server2:
    build: ./server
    links:
      - redis
      - redisses
      - cassandra
      # - mongo
    expose:
      - '3000'
    environment:
      - NAME=server2
      - MONGO_URL=mongodb://mongo:27017/sessions
  server3:
    build: ./server
    links:
      - redis
      - redisses
      - cassandra
      # - mongo
    expose:
      - '3000'
    environment:
      - NAME=server3
      - MONGO_URL=mongodb://mongo:27017/sessions
  server4:
    build: ./server
    links:
      - redis
      - redisses
      - cassandra
      # - mongo
    expose:
      - '3000'
    environment:
      - NAME=server4
      - MONGO_URL=mongodb://mongo:27017/sessions
  client:
    build: ./client
    links:
      - nginx
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    expose:
      - '6379'
  redisses:
    image: redis:alpine
    ports:
      - '6377:6377'
    expose:
      - '6377'
    command: --port 6377
  cassandra:
    image: cassandra
    # ports:
    #   - '9042:9042'
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=messages
    # expose:
    #   - '9042'
