nginx:
  image: nginx:alpine
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - server1
    - server2
    - server3
    - server4
  ports:
    - '3000:80'
  

server1:
  build: ./server
  links:
    - redis
  expose:
    - '3000'
  environment:
    - NAME=server1

server2:
  build: ./server
  links:
    - redis
  expose:
    - '3000'
  environment:
    - NAME=server2

server3:
  build: ./server
  links:
    - redis
  expose:
    - '3000'
  environment:
    - NAME=server3

server4:
  build: ./server
  links:
    - redis
  expose:
    - '3000'
  environment:
    - NAME=server4

client:
  build: ./client
  links:
    - nginx

redis:
  image: redis:alpine
  expose:
    - '6379'
